name: Release

on:
  release:
    types: [released]
  workflow_dispatch:
    inputs:
      TAG_NAME:
        description: "Tag name"
        required: true

env:
  REGISTRY: ghcr.io
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TAG_NAME: ${{ github.event.inputs.TAG_NAME || github.event.release.tag_name }}

jobs:
  retag-docker-image:
    runs-on: ubuntu-latest
    name: Retag Docker image as latest
    permissions:
      packages: write

    steps:
      - name: Set environment variables
        run: |
          echo VERSION=${TAG_NAME#v} >> $GITHUB_ENV
          echo IMAGE_NAME=$REGISTRY/$(echo ${GITHUB_REPOSITORY,,}) >> $GITHUB_ENV

      - name: Log in to the GitHub container registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ${{ env.REGISTRY }} -u ${{ github.repository_owner }} --password-stdin

      - name: Pull docker image
        run: docker pull ${{ env.IMAGE_NAME }}:v${{ env.VERSION }}

      - name: Tag docker image
        run: docker tag ${{ env.IMAGE_NAME }}:v${{ env.VERSION }} ${{ env.IMAGE_NAME }}:latest

      - name: Push docker image
        run: docker push ${{ env.IMAGE_NAME }}:latest
